module.exports = {
  apps: [
    {
      name: "ai-news",
      script: "src/index.js",
      cwd: ".",
      interpreter: "/Users/easthash/.nvm/versions/node/v24.16.0/bin/node",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      min_uptime: "10s",
      max_restarts: 20,
      restart_delay: 5000,
      kill_timeout: 8000,
      env: {
        NODE_ENV: "production",
        TELEGRAM_ENABLED: "true",
        TELEGRAM_SHARED_ENV_PATH: "/Users/easthash/code/telegramBot/.env",
        OPPORTUNITY_MONITOR_ENABLED: "true",
        OPPORTUNITY_HERMES_BIN: "/Users/easthash/.local/bin/hermes",
        OPPORTUNITY_HERMES_TIMEOUT_SEC: "600",
        HERMES_CODEX_EVENT_STALE_TIMEOUT_SECONDS: "60",
        OPPORTUNITY_INTERVAL_SEC: "86400",
        OPPORTUNITY_SCHEDULE_MODE: "daily_report",
        OPPORTUNITY_COLLECTION_TYPES: "launch,pre_tge",
        OPPORTUNITY_DAILY_REPORT_ENABLED: "true",
        OPPORTUNITY_DAILY_REPORT_TIME_BJ: "19:04",
        OPPORTUNITY_LOOKBACK_HOURS: "24",
        OPPORTUNITY_MAX_QUERY_JOBS: "3",
        OPPORTUNITY_FOCUSED_QUERIES_ENABLED: "false",
        OPPORTUNITY_MAX_FOLLOWUPS: "1",
        OPPORTUNITY_EXISTING_ENRICHMENT_MAX_ITEMS: "0",
        OPPORTUNITY_GROK_DEADLINE_FALLBACK_MAX: "1",
        OPPORTUNITY_QUOTA_ERROR_BACKOFF_SEC: "43200",
        BINANCE_MAJOR_NEWS_ENABLED: "true",
        BINANCE_MAJOR_NEWS_COLLECTION_TIME_BJ: "18:15",
        BINANCE_MAJOR_NEWS_DAILY_TIME_BJ: "19:01",
        BINANCE_MAJOR_NEWS_CHUNK_SIZE: "60",
        BINANCE_MAJOR_NEWS_MAX_ITEMS: "30",
        SECURITY_INCIDENT_MONITOR_ENABLED: "false",
        SECURITY_INCIDENT_INTERVAL_SEC: "1200"
      },
      out_file: "logs/engine.out.log",
      error_file: "logs/engine.err.log",
      merge_logs: true,
      time: true
    }
  ]
};
